# Generated by Django 5.2.4 on 2025-08-04 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Stock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True, verbose_name="交易日期")),
                ("open", models.FloatField(verbose_name="开盘价")),
                ("close", models.FloatField(verbose_name="收盘价")),
                ("high", models.FloatField(verbose_name="最高价")),
                ("low", models.FloatField(verbose_name="最低价")),
                ("volume", models.BigIntegerField(verbose_name="成交量")),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
        migrations.DeleteModel(
            name="Product",
        ),
    ]
