# Generated by Django 5.2.4 on 2025-08-04 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0002_stock_delete_product"),
    ]

    operations = [
        migrations.RenameField(
            model_name="stock",
            old_name="volume",
            new_name="total_trade_quantity",
        ),
        migrations.AddField(
            model_name="stock",
            name="last",
            field=models.FloatField(default=1, verbose_name="最后成交价"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="stock",
            name="turnover_lacs",
            field=models.FloatField(default=1, verbose_name="成交额（万）"),
            preserve_default=False,
        ),
    ]
